name: Deploy script to s3

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        default: 'dev'

jobs:
  deploy:
    name: Deploy script to dev

    runs-on: ubuntu-latest
#    environment: dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to s3
      run: echo "Hello world"

