name: Deploy to S3 with envs
on:
  push:
    branches: [ main ]

 # workflow_dispatch:
 #   inputs:
 #     environment:
 #       type: environment
 #       description: Select the environment
 #       default: 'dev'

jobs:
  read-package-json:
    name: Read JSON file
    runs-on: ubuntu-latest
    environment: dev

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: set-matrix
      run: |
        JSON=$(cat package.json)
        echo "::set-output name=matrix::${JSON//'%'/'%25'}"
        echo $matrix

  build:
    needs: read-package-json
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.read-package-json.outputs.matrix) }}
    environment: dev
    env:
      version: ${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: echo $version